# Generated by Django 2.2.6 on 2020-07-27 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Management', '0001_initial'),
        ('Education', '0001_initial'),
        ('Administration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_questions_set', to='Education.Course')),
            ],
        ),
        migrations.CreateModel(
            name='CourseResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=10, unique=True)),
                ('internal_marks', models.IntegerField()),
                ('external_marks', models.IntegerField()),
                ('total_marks', models.IntegerField()),
                ('grade', models.CharField(max_length=10)),
                ('percentage', models.FloatField()),
                ('passed', models.BooleanField(default=False)),
                ('present_marks', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_results', to='Education.Course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registered_courses', to='Administration.Channel')),
            ],
        ),
        migrations.CreateModel(
            name='ParseQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TestAnswerSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_code', models.CharField(max_length=10)),
                ('course_name', models.CharField(max_length=100)),
                ('credentials', models.CharField(max_length=100, unique=True)),
                ('uploaded_by', models.CharField(max_length=100)),
                ('answers', models.TextField(blank=True, max_length=300)),
                ('is_submitted', models.BooleanField(default=False)),
                ('submitted_on', models.DateTimeField(auto_now=True)),
                ('score', models.IntegerField(default=0)),
                ('show_result', models.BooleanField(default=False)),
                ('grade', models.CharField(blank=True, max_length=4)),
                ('is_drafted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TestQuestionPaper',
            fields=[
                ('paper_code', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('duration', models.FloatField()),
                ('no_of_questions', models.IntegerField()),
                ('max_marks', models.IntegerField()),
                ('uploaded_on', models.DateTimeField(auto_now=True)),
                ('message', models.TextField(blank=True, max_length=300)),
                ('answersheets', models.ManyToManyField(blank=True, to='Examination.TestAnswerSheet')),
                ('course_questions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_tests', to='Examination.CourseQuestions')),
                ('reports', models.ManyToManyField(blank=True, to='Management.Report')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('is_script', models.BooleanField(default=False)),
                ('is_blank', models.BooleanField(default=False)),
                ('is_choice', models.BooleanField(default=False)),
                ('question_code', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('question', models.TextField(max_length=500)),
                ('option1', models.CharField(blank=True, max_length=100, null=True)),
                ('option2', models.CharField(blank=True, max_length=100, null=True)),
                ('option3', models.CharField(blank=True, max_length=100, null=True)),
                ('option4', models.CharField(blank=True, max_length=100, null=True)),
                ('answer', models.CharField(max_length=500)),
                ('marks', models.IntegerField()),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_questions', to='Education.Course')),
            ],
        ),
        migrations.CreateModel(
            name='FinalResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.FloatField(blank=True, null=True)),
                ('gpa', models.FloatField(blank=True, null=True)),
                ('is_promoted', models.BooleanField(default=False)),
                ('courses_result', models.ManyToManyField(blank=True, to='Examination.CourseResult')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='channel_progress_card', to='Administration.Channel')),
            ],
        ),
        migrations.AddField(
            model_name='coursequestions',
            name='questions',
            field=models.ManyToManyField(blank=True, to='Examination.Question'),
        ),
    ]
