# Generated by Django 2.2.6 on 2020-07-27 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Administration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeReminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_sent', models.BooleanField(default=False)),
                ('month', models.CharField(max_length=20, unique=True)),
                ('sent_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(blank=True)),
                ('transaction_code', models.CharField(max_length=40)),
                ('paid_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TutionFee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_number', models.IntegerField()),
                ('month', models.CharField(max_length=12)),
                ('paid', models.BooleanField(default=False)),
                ('transaction', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Transactions.Transaction')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=100, unique=True)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField()),
                ('channel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='channel_payment_card', to='Administration.Channel')),
                ('tution_fee', models.ManyToManyField(blank=True, to='Transactions.TutionFee')),
            ],
        ),
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_fee', models.FloatField()),
                ('tution_fee', models.FloatField()),
                ('admission_fee', models.FloatField()),
                ('standard', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='standard_fee_structure', to='Administration.Standard')),
            ],
        ),
    ]
