# Generated by Django 2.2.6 on 2020-07-27 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Management', '0001_initial'),
        ('Examination', '0001_initial'),
        ('DashBoard', '0001_initial'),
        ('Education', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40, unique=True)),
                ('key', models.CharField(max_length=100, unique=True)),
                ('standard', models.IntegerField()),
                ('answersheets', models.ManyToManyField(blank=True, to='Examination.TestAnswerSheet')),
                ('assignments', models.ManyToManyField(blank=True, to='Education.AssignmentDocument')),
                ('circulars', models.ManyToManyField(blank=True, to='DashBoard.Circular')),
                ('events', models.ManyToManyField(blank=True, to='Management.Event')),
                ('individual_messages', models.ManyToManyField(blank=True, to='DashBoard.IndividualMessage')),
                ('notifications', models.ManyToManyField(blank=True, to='DashBoard.Notification')),
                ('reminders', models.ManyToManyField(blank=True, to='DashBoard.Reminder')),
                ('tutorials', models.ManyToManyField(blank=True, to='Education.PostTutorial')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LeaveForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True, max_length=400)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('is_granted', models.BooleanField(default=False)),
                ('applied_on', models.DateTimeField(auto_now=True)),
                ('channelcontent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_form', to='Main.ChannelContent')),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('KEY', models.CharField(default='#h@&!%2000{}*^~\theddu', max_length=20, unique=True)),
                ('ADMIN', models.CharField(max_length=50)),
                ('PASSWORD', models.CharField(max_length=14)),
                ('RESULTS_SESSION', models.BooleanField(default=False)),
                ('ADMISSIONS_SESSION', models.BooleanField(default=False)),
                ('GOOGLE_SHEET_NAME', models.CharField(blank=True, max_length=50, null=True)),
                ('GOOGLE_SHEET_CREDENTIALS_PATH', models.FilePathField()),
                ('CLEAR_DATABASE', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='StaffChannelContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40, unique=True)),
                ('key', models.CharField(max_length=100, unique=True)),
                ('standard', models.IntegerField()),
                ('circulars', models.ManyToManyField(blank=True, to='DashBoard.Circular')),
                ('courses', models.ManyToManyField(blank=True, to='Education.Course')),
                ('events', models.ManyToManyField(blank=True, to='Management.Event')),
                ('individual_messages', models.ManyToManyField(blank=True, to='DashBoard.IndividualMessage')),
                ('leave_letters', models.ManyToManyField(blank=True, to='Main.LeaveForm')),
                ('notifications', models.ManyToManyField(blank=True, to='DashBoard.Notification')),
                ('posted_assignments', models.ManyToManyField(blank=True, to='Education.PostAssignment')),
                ('posted_tests', models.ManyToManyField(blank=True, to='Examination.TestQuestionPaper')),
                ('posted_tuttorials', models.ManyToManyField(blank=True, to='Education.PostTutorial')),
                ('reminders', models.ManyToManyField(blank=True, to='DashBoard.Reminder')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StaffLeaveForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True, max_length=400)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('is_granted', models.BooleanField(default=False)),
                ('applied_on', models.DateTimeField(auto_now=True)),
                ('channelcontent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.StaffChannelContent')),
            ],
        ),
    ]
