# Generated by Django 2.2.6 on 2020-07-27 01:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_number', models.CharField(max_length=10, unique=True)),
                ('fullname', models.CharField(max_length=50)),
                ('father_name', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('APPLIED', 'APPLIED'), ('VERIFIED', 'VERIFIED'), ('PROCEDING', 'PROCEDING'), ('ADMITTED', 'ADMITTED'), ('REJECTED', 'REJECTED')], default='APPLIED', max_length=50)),
                ('email_id', models.EmailField(max_length=50)),
                ('mobile_number', models.CharField(max_length=20)),
                ('standard', models.IntegerField()),
                ('date', models.DateField(auto_now=True)),
                ('approved', models.BooleanField(default=False)),
                ('msg_sent', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ChangeMobileNumberForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(max_length=500)),
                ('new_number', models.TextField(max_length=500)),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('username', models.CharField(max_length=40, unique=True, validators=[django.core.validators.MaxLengthValidator(15, message='Username is too long'), django.core.validators.MinLengthValidator(6, message='Username is too short..')])),
                ('father_name', models.CharField(max_length=50)),
                ('mother_name', models.CharField(max_length=50)),
                ('caste', models.CharField(choices=[('SC', 'SC'), ('ST', 'ST'), ('BC-A', 'BC-A'), ('BC-B', 'BC-B'), ('BC-CBC-D', 'BC-CBC-D'), ('BC-E', 'BC-E'), ('OC', 'OC'), ('OBC', 'OBC')], max_length=50)),
                ('key', models.CharField(max_length=100, unique=True)),
                ('profile', models.ImageField(blank=True, max_length=300, null=True, upload_to='DataProcessorSystem/StaticDataProcessor/uploads/profiles/')),
                ('email', models.EmailField(max_length=200)),
                ('admission_number', models.CharField(blank=True, max_length=10, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PRIMARY_TEACHER', 'PRIMARY_TEACHER'), ('SECONDARY_TEACHER', 'SECONDARY_TEACHER'), ('ACCOUNTANT', 'ACCOUNTANT'), ('PRINICIPAL', 'PRINICIPAL'), ('VICE-PRINCIPAL', 'VICE-PRINCIPAL'), ('MANAGER', 'MANAGER'), ('STUDENT', 'STUDENT')], max_length=20)),
                ('is_staff', models.BooleanField(default=False)),
                ('section', models.CharField(choices=[('A', 'A'), ('B', 'B')], max_length=1)),
                ('rollnumber', models.IntegerField(blank=True)),
                ('mobile_number', models.CharField(max_length=20, validators=[django.core.validators.MaxLengthValidator(12, message='Too Long'), django.core.validators.MinLengthValidator(10, message='too short..')])),
                ('language', models.CharField(choices=[('Telugu', 'Telugu'), ('Hindi', 'Hindi'), ('English', 'English')], max_length=50)),
                ('date_of_join', models.DateField(auto_now=True)),
                ('is_manager', models.BooleanField(default=False)),
                ('password', models.CharField(default='password', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TCForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(max_length=500)),
                ('applied_on', models.DateField(auto_now=True)),
                ('granted', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('APPLIED', 'APPLIED'), ('VERIFIED AT EXAMINATION', 'VERIFIED AT EXAMINATION'), ('VERIFIED BY TRANSACTIONS', 'VERIFIED BY TRANSACTIONS'), ('VERIFIED BY VICE CHANCELLORGRANTED', 'VERIFIED BY VICE CHANCELLORGRANTED')], max_length=40)),
                ('fee_section', models.BooleanField(default=False)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_TCForm', to='Administration.Channel')),
            ],
        ),
        migrations.CreateModel(
            name='Standard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard', models.IntegerField(unique=True)),
                ('incharge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='standard_incharge', to='Administration.Channel')),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_forms', models.ManyToManyField(blank=True, to='Administration.AdmissionForm')),
                ('channel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Administration.Channel')),
                ('cm_forms', models.ManyToManyField(blank=True, to='Administration.ChangeMobileNumberForm')),
                ('tc_forms', models.ManyToManyField(blank=True, to='Administration.TCForm')),
            ],
        ),
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField(max_length=500)),
                ('on', models.DateTimeField(auto_now=True)),
                ('is_drafted', models.BooleanField(default=False)),
                ('reply_text', models.TextField(blank=True, max_length=500, null=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_feedback', to='Administration.Channel')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('vision', models.CharField(max_length=300)),
                ('message', models.CharField(max_length=150)),
                ('head', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='head_of_department', to='Administration.Channel')),
                ('members', models.ManyToManyField(blank=True, related_query_name='all_members', to='Administration.Channel')),
            ],
        ),
        migrations.AddField(
            model_name='channel',
            name='standard',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='standard_students', to='Administration.Standard'),
        ),
        migrations.AddField(
            model_name='changemobilenumberform',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_mobile_number', to='Administration.Channel'),
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(max_length=500)),
                ('on_date', models.DateField()),
                ('session', models.CharField(max_length=40)),
                ('applied_on', models.DateTimeField(auto_now=True)),
                ('success', models.BooleanField(default=False)),
                ('msg_sent', models.BooleanField(default=False)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_appointment', to='Administration.Channel')),
            ],
        ),
    ]
