"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 2.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '=wr2@_(eor!#+fg**7fl*s97!**kd(%9zb*@xj66e@2k4m9_hj'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
'www.prince.com',
'127.0.0.1'
]

#A list of all the people who get code error notifications. When DEBUG=False
ADMINS =[
  ('srihari','sriharitheddu02@gmail.com'),
]


#A string containing a dotted path to a function (or any callable) that defines how to compose a prefix, version and key into a final cache key. The default implementation is equivalent to the function
KEY_PREFIX = 'HARI@360'



#---------------------------------
# Application definition
from mysite.coresettings.appconf import (
        Main,
        Administration,
        Examination,
        Education,
        Transactions,
        Management,
        DashBoard,
        DATABASE_CONFIG
        )

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
]

#Installing Administration App
if Main.install:
	INSTALLED_APPS.append('Applications.Main')
	
else:
	pass

#Installing Administration App
if Administration.install:
	INSTALLED_APPS.append('Applications.Administration')
	
else:
	pass
	
#Installing Administration App
if Examination.install:
	INSTALLED_APPS.append('Applications.Examination')
else:
	pass
	
#Installing Administration App	
if Transactions.install:
	INSTALLED_APPS.append('Applications.Transactions')
else:
	pass	

#Installing Administration App
if Education.install:
	INSTALLED_APPS.append('Applications.Education')
else:
	pass	

#Installing Administration App
if Management.install:
	INSTALLED_APPS.append('Applications.Management')
else:
	pass	

if DashBoard.install:
	INSTALLED_APPS.append('Applications.DashBoard')
else:
	pass
#----------------------------------
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
        
        os.path.join(BASE_DIR,'DataProcessorSystem/TemplateEngineSystem/Templates/Maintainence'),
        os.path.join(BASE_DIR,'DataProcessorSystem/TemplateEngineSystem/Templates/Administration'),
        os.path.join(BASE_DIR,'DataProcessorSystem/TemplateEngineSystem/Templates/Education'),
        os.path.join(BASE_DIR,'DataProcessorSystem/TemplateEngineSystem/Templates/Examination'),
        os.path.join(BASE_DIR,'DataProcessorSystem/TemplateEngineSystem/Templates/Transaction'),
        os.path.join(BASE_DIR,'DataProcessorSystem/TemplateEngineSystem/Templates/Management'),
       os.path.join(BASE_DIR,'DataProcessorSystem/TemplateEngineSystem/Templates/DashBoard') 
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        'libraries':{
         'my_tags':'DataProcessorSystem.TemplateEngineSystem.Tags.__init__',

        },
        },
    },
]

WSGI_APPLICATION = 'mysite.wsgi.application'

#Cache Handler Installation
#Internal Django site
#After Installing this run command
#python manage.py createcachetable

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
        'LOCATION':'my_cache_table',
   'TIMEOUT': 1000000,
        'OPTIONS': {
            'MAX_ENTRIES': 1000
        }
    }
}

#Messages Relted Middleware

from django.contrib import messages

#MESSAGE_STORAGE = 'django.contrib.messages.storage.fallback.FallbackStorage'


MESSAGE_TAGS = {
    messages.DEBUG: 'debug',
    messages.INFO: 'info',
    messages.SUCCESS: 'success',
    messages.WARNING: 'warning',
    messages.ERROR: 'error',
}

# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

if DATABASE_CONFIG:
	DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'prince',
        'USER':'hariwwe',
        'PASSWORD':"#hari@360",
        'HOST':'localhost'
        }
    }
    
else:
	DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'


TIME_ZONE = 'America/Chicago'


USE_I18N = True

USE_L10N = True

USE_TZ = True


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/emailbackends/

EMAIL_BACKEND = 'django.core.mail.backends.filebased.EmailBackend'

#The output will be storedm...
EMAIL_FILE_PATH = os.path.join(BASE_DIR,'DataProcessorSystem/Messages')
# change this to a proper location

#The host to use for sending email.
EMAIL_HOST = 'localhost'

#The host to use for sending email.
EMAIL_HOST_USER = 'testmyserver2020@gmail.com'

#Password to use for the SMTP server defined in EMAIL_HOST.
EMAIL_HOST_PASSWORD = '#server2020'

EMAIL_USE_LOCALTIME = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
   os.path.join(BASE_DIR,'DataProcessorSystem/StaticDataProcessor/designs/'),
   
   
]

STATIC_ROOT = os.path.join('DataProcessorSystem/StaticDataProcessor')

#media for the devolpment level

MEDIA_URL = '/media/'

MEDIA_ROOT = os.path.join(BASE_DIR,'DataProcessorSystem/MediaDataProcessor')



#The maximum size (in bytes) that an upload will be before it gets streamed to the file system.
FILE_UPLOAD_MAX_MEMORY_SIZE = 4621440
#(3.5mb)

FIRST_DAY_OF_WEEK = 0
#0(sunday)-6(saturday)


#used to load fixture data
FIXTURE_DIRS = [
    os.path.join(BASE_DIR,'DataProcessorSystem/FixturesInstallation')
]

