# Generated by Django 2.2.6 on 2020-07-27 01:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Administration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.TextField(max_length=200)),
                ('vision', models.TextField(max_length=500)),
                ('date', models.DateTimeField()),
                ('image', models.ImageField(blank=True, max_length=400, null=True, upload_to='DataProcessorSystem/StaticDataProcessor/uploads/postures/')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.CharField(max_length=40, null=True)),
                ('sport', models.CharField(max_length=40, null=True)),
                ('is_captain', models.BooleanField(default=False)),
                ('is_vice_captain', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administration.Channel')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_number', models.IntegerField()),
                ('content', models.TextField(max_length=500)),
                ('reported_on', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport', models.CharField(max_length=100)),
                ('vision', models.TextField(max_length=500)),
                ('password', models.CharField(max_length=12, validators=[django.core.validators.MaxLengthValidator(11, message='Your Mobile Number is Too Long'), django.core.validators.MinLengthValidator(8, message='Your Mobile Number is too short..')])),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coach', to='Administration.Channel')),
                ('incharges', models.ManyToManyField(blank=True, related_query_name='incharges_of_team', to='Administration.Channel')),
                ('players', models.ManyToManyField(related_query_name='co-ordinators_in_management', to='Management.Player')),
            ],
        ),
        migrations.CreateModel(
            name='Management',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('co_ordinaters', models.ManyToManyField(related_query_name='co-ordinators_in_management', to='Administration.Channel')),
                ('head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='head_of_management', to='Administration.Channel')),
            ],
        ),
        migrations.CreateModel(
            name='EventRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('admission_number', models.IntegerField()),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standard_events', to='Administration.Standard')),
                ('this_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_to_register', to='Management.Event')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='management',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='Management.Management'),
        ),
        migrations.AddField(
            model_name='event',
            name='participents',
            field=models.ManyToManyField(blank=True, to='Management.EventRegister'),
        ),
    ]
