# Generated by Django 2.2.6 on 2020-07-27 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Management', '0001_initial'),
        ('Administration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100)),
                ('references', models.TextField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100)),
                ('course_code', models.CharField(max_length=6)),
                ('outcomes', models.TextField(max_length=1000)),
                ('content', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Education.Content')),
                ('incharge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_courses', to='Administration.Channel')),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standard_courses', to='Administration.Standard')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('introduction', models.TextField(blank=True, max_length=500)),
                ('information', models.FileField(blank=True, max_length=300, null=True, upload_to='uploads/')),
                ('practice_questions', models.TextField(blank=True, max_length=1000, null=True)),
                ('summary', models.TextField(blank=True, max_length=1000, null=True)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_units', to='Education.Course')),
                ('this_content', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_units', to='Education.Content')),
            ],
        ),
        migrations.CreateModel(
            name='PostTutorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=150)),
                ('information', models.FileField(blank=True, max_length=300, null=True, upload_to='uploads/')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_tutorials', to='Education.Course')),
                ('reports', models.ManyToManyField(blank=True, to='Management.Report')),
            ],
        ),
        migrations.CreateModel(
            name='PostAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=50, unique=True)),
                ('question', models.TextField(max_length=500)),
                ('message', models.TextField(blank=True, max_length=500)),
                ('due_date', models.DateTimeField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_assignments', to='Education.Course')),
                ('reports', models.ManyToManyField(blank=True, to='Management.Report')),
            ],
        ),
        migrations.AddField(
            model_name='content',
            name='posted_tutorials',
            field=models.ManyToManyField(blank=True, to='Education.PostTutorial'),
        ),
        migrations.AddField(
            model_name='content',
            name='units',
            field=models.ManyToManyField(blank=True, to='Education.Unit'),
        ),
        migrations.CreateModel(
            name='AssignmentDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('credentials', models.CharField(max_length=100, unique=True)),
                ('document', models.FileField(blank=True, max_length=500, null=True, upload_to='uploads/')),
                ('is_submitted', models.BooleanField(default=False)),
                ('uploaded_on', models.DateTimeField(auto_now=True)),
                ('course_name', models.CharField(max_length=50)),
                ('is_drafted', models.BooleanField(default=False)),
                ('qas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='Education.PostAssignment')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_documents', to='Administration.Channel')),
            ],
        ),
    ]
